import { JetBrains_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/Header";
import PageTransition from "@/components/PageTransition";
import StairTransition from "@/components/StairTransition";
import CustomCursor from "@/components/CustomCursor";
import { Toaster } from 'react-hot-toast'



const jetbrainsMono = JetBrains_Mono({
  variable: "--font-jetbrainsMono",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800"]
});

export const metadata = {
  title: "Imam Hossen Portfolio",
  description: "Generated by create next app",
};


export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={jetbrainsMono.variable}
      >
        <Header />
        <StairTransition />
        <CustomCursor />
        <Toaster
          position="top-center"
          toastOptions={{
            className: '',
            duration: 3000,
            style: {
              background: '#27272c',
              color: '#fff',
              fontFamily: 'var(--font-jetbrainsMono)',
              fontSize: '16px',
            },
          }}
        />
        <PageTransition>
          {children}

        </PageTransition>
      </body>
    </html>
  );
}
